# GitLab CI/CD Pipeline for HyperScale Platform

variables:
  AWS_REGION: us-east-1
  ECR_REGISTRY: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
  IMAGE_NAME: hyperscale/api-service
  EKS_CLUSTER: hyperscale-eks

stages:
  - test
  - build
  - scan
  - deploy

# Cache dependencies
cache:
  paths:
    - .pip-cache/

# Lint and test
lint:
  stage: test
  image: python:3.11-slim
  script:
    - pip install pylint
    - pylint --rcfile=.pylintrc **/*.py
  allow_failure: true

unit-test:
  stage: test
  image: python:3.11-slim
  script:
    - pip install -r requirements.txt pytest pytest-cov
    - pytest tests/ --cov=. --cov-report=xml --cov-report=term
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

# Build Docker image
build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apk add --no-cache git
  script:
    - export IMAGE_TAG=$(git rev-parse --short HEAD)-${CI_PIPELINE_ID}
    - docker build -t ${IMAGE_NAME}:${IMAGE_TAG} -f docker/api-service/Dockerfile .
    - docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${IMAGE_NAME}:latest
    - docker save ${IMAGE_NAME}:${IMAGE_TAG} > image.tar
  artifacts:
    paths:
      - image.tar
    expire_in: 1 day
  only:
    - main
    - develop

# Security scanning
trivy-scan:
  stage: scan
  image: aquasec/trivy:latest
  dependencies:
    - build
  script:
    - docker load < image.tar
    - trivy image --severity HIGH,CRITICAL --exit-code 0 ${IMAGE_NAME}:latest
  allow_failure: true
  only:
    - main
    - develop

# Deploy to EKS
deploy-production:
  stage: deploy
  image: amazon/aws-cli:latest
  before_script:
    - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    - chmod +x kubectl
    - mv kubectl /usr/local/bin/
  script:
    - export IMAGE_TAG=$(git rev-parse --short HEAD)-${CI_PIPELINE_ID}
    # Login to ECR
    - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_REGISTRY}
    # Load and push image
    - docker load < image.tar
    - docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${ECR_REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}
    - docker push ${ECR_REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}
    # Update EKS deployment
    - aws eks update-kubeconfig --name ${EKS_CLUSTER} --region ${AWS_REGION}
    - kubectl set image deployment/api-service api=${ECR_REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG} -n production
    - kubectl rollout status deployment/api-service -n production --timeout=5m
  dependencies:
    - build
  only:
    - main
  environment:
    name: production
    url: https://api.hyperscale.example.com

deploy-staging:
  stage: deploy
  image: amazon/aws-cli:latest
  script:
    - echo "Deploy to staging environment"
    # Staging deployment logic here
  only:
    - develop
  environment:
    name: staging
    url: https://staging-api.hyperscale.example.com
